version: "3.7"
services:
  jenkins:
    container_name: jenkins
    image: "jenkins:2.60.3"
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    environment:
      - TZ=Asia/seoul
    restart: always
